---
- name: Converge
  hosts: targetnodes
  become: true
  vars:
    route53_ddns_route53zonename: "{{ lookup('env', 'ROUTE53_ZONENAME') }}"
    route53_ddns_route53zoneid: "{{ lookup('env', 'ROUTE53_ZONEID') }}"
    route53_ddns_hostname: "{{ inventory_hostname_short }}-{{ lookup('env', 'ANSIBLE_VERSION') }}"
    route53_ddns_win_user: runneradmin
    route53_ddns_win_group: Administrators
  pre_tasks:
    - name: All pre_tasks
      block:
        # - name: Check environment info
        #   ansible.builtin.shell: |
        #     whoami
        #     pwd
        #     env
        #   changed_when: false
        #   become: false
        #   register: checkenvironment

        - name: Update apt cache.
          ansible.builtin.apt: update_cache=yes cache_valid_time=600
          when: ansible_os_family == 'Debian'

        - name: Wait for systemd to complete initialization.  # noqa 303
          ansible.builtin.command: systemctl is-system-running
          register: systemctl_status
          until: >
            'running' in systemctl_status.stdout or
            'degraded' in systemctl_status.stdout
          retries: 40
          delay: 5
          when: ansible_service_mgr == 'systemd'
          changed_when: false
          failed_when: systemctl_status.rc > 1

        - name: fix coreutils-single on containers
          ansible.builtin.command: dnf install -y --allowerasing coreutils
          when:
            - ansible_os_family == 'RedHat'
            - ansible_distribution_major_version| int > 7
          changed_when: false
      when:
        - ansible_system == "Linux" or ansible_distribution == "MacOSX"
      tags:
        - always
  roles:
    - role: sdarwin.route53_dynamic_dns
