---
name: CI
'on':
  pull_request:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  mac_clients:
    name: MacOSX Clients
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
    steps:
      - name: Test IP
        run: |
          set -xe
          for i in {1..20}; do
             curl https://ipinfo.io/ip
             sleep 5
          done
